// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import '@hotwired/stimulus'
import "controllers"
import "@carbon/web-components/dist/button.min.js"
import "@carbon/web-components/dist/link.min.js"
import "@carbon/web-components/dist/ui-shell.min.js"
import "@carbon/web-components/dist/notification.min.js"
import "@carbon/web-components/dist/form.min.js"
import "@carbon/web-components/dist/input.min.js"
import "@carbon/web-components/dist/textarea.min.js"
import "@carbon/web-components/dist/list.min.js"
import "@carbon/web-components/dist/tile.min.js"
import "@carbon/web-components/dist/file-uploader.min.js"
import "@carbon/web-components/dist/tag.min.js"
import "@carbon/web-components/dist/modal.min.js"
import "@carbon/web-components/dist/checkbox.min.js"
import "@carbon/web-components/dist/search.min.js"
import 'bootstrap'