// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "@carbon/web-components/dist/button.min.js"
import "@carbon/web-components/dist/link.min.js"
import "@carbon/web-components/dist/ui-shell.min.js"
import "@carbon/web-components/dist/notification.min.js"
import "@carbon/web-components/dist/form.min.js"
import "@carbon/web-components/dist/input.min.js"
import "@carbon/web-components/dist/textarea.min.js"